### ISSUE TITLE
Use vNic Profile in in source network mappings

### ISSUE THREAD

**Issue by masayag** [kubevirt/vm-import-operator#111]
Instead using networks within networkMappings, we need to have the vnic profile as identifier of that network, since it is possible that two vnic profiles of the same network will be mapped to two different network attachment definition resources on kubevirt.

**Comment by pkliczewski** [comment]
@suomiy FYI

**Comment by pkliczewski** [comment]
This PR https://github.com/ManageIQ/manageiq-v2v-conversion_host/pull/51 enables UI to use vNicProfile.

**Comment by atiratree** [comment]
UI PR: https://github.com/openshift/console/pull/5277
