### ISSUE TITLE
Allow SR-IOV during import

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/vm-import-operator#112]
Support for SR-IOV will be available within the same release as `vm-import-operator` and we should allow it.

**Comment by pkliczewski** [comment]
@jakub-dzon FYI

**Comment by jakub-dzon** [comment]
It includes also updating the validation rules documentation, where it is explicitly written that we don't support SR-IOV.

**Comment by pkliczewski** [comment]
@dankenigsberg @phoracek please help us understand what we should copy from RHV so we can enable vm with SRIOV configuation to be imported.

**Comment by dankenigsberg** [comment]
> @dankenigsberg @phoracek please help us understand what we should copy from RHV so we can enable vm with SRIOV configuation to be imported.

I'm not sure I understand your question. If you see that the oVirt VM has a vNIC with a `passthrough` profile, you should convert it to a KubeVirt vNIC with `sriov` binding method and connect it to a NetworkAttachementDefintion of type `sriov`.

@AlonaKaplan can help you with more detail about the oVirt API and KubeVirt API alike.

**Comment by AlonaKaplan** [comment]
@pkliczewski besides what Dan wrote you need to find the relevant NetworkAttachementDefintion to connect the vnic to.
How do you map oVirt's logical network to kubevit's NetworkAttachementDefintion when you import a non-sriov vnics?

* More details of how to configure sriov vnic in kubevirt can be found [here](https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=sriov).

**Comment by pkliczewski** [comment]
@AlonaKaplan [here](https://github.com/kubevirt/vm-import-operator/blob/e6af7681567fc4f14f2dfdf1b53c7fab2ca9e9a6/pkg/providers/ovirt/mapper/mapper.go#L321) is network mapping code. We do not have RHV nor CNV environment with SRIOV to test our changes. 

There is one more change which needs to be done to enable the import. We need to remove [this](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/providers/ovirt/validation/validators/nic-validator.go#L104) method.

Once both changes are done SRIOV import will work.

**Comment by AlonaKaplan** [comment]
@pkliczewski can you please send me a link to the code that creates [o.mappings.NetworkMappings](https://github.com/kubevirt/vm-import-operator/blob/e6af7681567fc4f14f2dfdf1b53c7fab2ca9e9a6/pkg/providers/ovirt/mapper/mapper.go#L358)"? So I will see how you map NetworkAttachment to VnicProfile and will see if it should be adjusted to support sriov.

Anyway, the [mapNics](https://github.com/kubevirt/vm-import-operator/blob/e6af7681567fc4f14f2dfdf1b53c7fab2ca9e9a6/pkg/providers/ovirt/mapper/mapper.go#L310) should be changed. In case of passthough vnicProfile the `InterfaceBindingMethod` should be `InterfaceSRIOV` and not `InterfaceBridge`

**Comment by pkliczewski** [comment]
> @pkliczewski can you please send me a link to the code that creates [o.mappings.NetworkMappings](https://github.com/kubevirt/vm-import-operator/blob/e6af7681567fc4f14f2dfdf1b53c7fab2ca9e9a6/pkg/providers/ovirt/mapper/mapper.go#L358)"? So I will see how you map NetworkAttachment to VnicProfile and will see if it should be adjusted to support sriov.

This information is provided by the user either in internal or external mapping. Please take a look [here](https://github.com/kubevirt/vm-import-operator/blob/master/docs/design.md#resource-mappings).

> 
> Anyway, the [mapNics](https://github.com/kubevirt/vm-import-operator/blob/e6af7681567fc4f14f2dfdf1b53c7fab2ca9e9a6/pkg/providers/ovirt/mapper/mapper.go#L310) should be changed. In case of passthough vnicProfile the `InterfaceBindingMethod` should be `InterfaceSRIOV` and not `InterfaceBridge`

How can we verify that it works?

**Comment by AlonaKaplan** [comment]
You will need a cluster with sriov network operator. You can create one using [kubevirtci](https://github.com/kubevirt/kubevirtci/tree/master/cluster-up/cluster/kind-k8s-sriov-1.17.0).

If you just want to verify the import, I think a regular non-sriov server for the cluster should be enough. You will have to apply `SriovNetwork` which will be translated to `NetworkAttachmentDefinition`.
Update the `NetworkAttachment` to `VnicProfile` mapping and than do the import.
 
If you want to run the imported vm, you will need a node with sriov enabled and `SriovNetworkNodePolicy` applied.

**Comment by pkliczewski** [comment]
@AlonaKaplan Thanks for the input. I think we will target next release with the changes you suggested.
