### ISSUE TITLE
Processing condition stuck in CopyingDisks

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#119]
Does it make sense to fail the import if we detect that CDI importer pod falls into CrashLoopBackOff ? Because the phase of datavolume stays like this
```yaml
  phase: ImportInProgress
  progress: N/A
```

relevant bug: https://github.com/kubevirt/containerized-data-importer/issues/1187

**Comment by pkliczewski** [comment]
Yes, we need to fail the import process.

**Comment by pkliczewski** [comment]
It seems like we need to specify timeout how long we are going to wait on the import.

**Comment by atiratree** [comment]
I agree, there could be a long timeout to check if the import starts at all. 

But IMO it also make sense to see if importer pod got into CrashLoopBackOff as it is a kubernetes way to check that the pod restarted few times but failed every time - this would cause the import to fail faster

**Comment by pkliczewski** [comment]
@suomiy Is there any way to correlate `DV`s with an imported pod?

**Comment by atiratree** [comment]
You can get it in PVC's annotation 
```
cdi.kubevirt.io/storage.import.importPodName: importer-6e79a7a9-c4e2-41ce-a857-9d992c55298b
```

PVC's name should be the same as DataVolume one: `6e79a7a9-c4e2-41ce-a857-9d992c55298b` plus DV is the owner of that PVC.

**Comment by machacekondra** [comment]
We have to options how to solve the issue:

1) As reconcile can handle only single type, and we use reconcile for VMImport type already, we can't add watch like:
```go
err = c.Watch(
		&source.Kind{Type: &corev1.Pod{}},
		&handler.EnqueueRequestForOwner{
			IsController: true,
			OwnerType:    &corev1.PersistentVolumeClaim{},
		},
	)
```
So we would need to use `handler.EnqueueRequestsFromMapFunc`, but actually there is no correllation between PVC import pod and VMImport CR object, so we would need to add support to CDI to pass the annoations/labels to import pods from the DV, so we can map imported to VMImport CR instance.

2) Add new controller which will watch for PVC import pods and update VMImport CR accordingly.

**Comment by pkliczewski** [comment]
1. may make our code a bit more complex
2. may create time based issues between controllers with better defined responsibilities

@machacekondra which one in your opinion would be simpler to implement and maintain?

**Comment by machacekondra** [comment]
I think 1. is better, I will ask CDI guys, what they think of feature to propagating labels or annotations to importer pod from datavolume.
