### ISSUE TITLE
VirtualMachineImport are not processed and stuck forever

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#121]
When one VirtualMachineImport fails with following error https://github.com/kubevirt/vm-import-operator/issues/120#issue-603863544 (please see log), then any new VirtualMachineImport stays unprocessed and without any conditions.

**Comment by pkliczewski** [comment]
We need to handle situation when a vm was not created and mark the import as failed.

**Comment by atiratree** [comment]
edited: ~not relevant: I was not using vmimport-os-mapper config map before, but after creating it~ I cannot reproduce this anymore

should I close this issue?

**Comment by atiratree** [comment]
not reproducible at the moment
