### ISSUE TITLE
Decouple controller and provider

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/vm-import-operator#125]
At the moment provider life cycle depends on `Reconcile` progress. It is not possible to mock the provider so we introduced ClientFactory to mock the client inside of it. This would make provider testable outside of the scope of controller.

**Comment by jakub-dzon** [comment]
The controller should not be aware of client interface or client factory, which should be implementation details of the oVirt provider and at the same time both OvirtProvider and Reconcile should be unit-testable.
