### ISSUE TITLE
disk import progress does not show any change until CDI import completes

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#126]
depends on: 
* https://github.com/kubevirt/containerized-data-importer/issues/1190
* https://bugzilla.redhat.com/1826381

**Comment by pkliczewski** [comment]
@suomiy I think we have a duplicate with https://github.com/kubevirt/vm-import-operator/issues/124. Please use one issue to track this item.

**Comment by atiratree** [comment]
@pkliczewski this is a different issue about progress not being reported. 
#124 is about how much of progress bar disk import should take - currently just jumps from 40-90 at the end.

**Comment by pkliczewski** [comment]
@suomiy OK, let's keep both.

**Comment by pkliczewski** [comment]
CDI fixed progress reporting with https://github.com/kubevirt/containerized-data-importer/pull/1191. We have no pending dependencies to solve this issue now.
