### ISSUE TITLE
VM initialization configuration

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#163]
Source Vm.initialization (cloud init) configuration in not mapped to target VM.

**Comment by pkliczewski** [comment]
The question is whether we want to map it. Do we assume the vm may be not initialized?

**Comment by jakub-dzon** [comment]
It might be an edge case and not the 1st priority feature gap.

I can imagine two cases where it is needed:

1. If the VM is migrated and we don't warn the user that some configuration will be lost, he might expect to find that configuration in the target VM; the disappointment would be greater if the user removed the source VM;
1. User creates stopped VMs in oVirt because it's easier for him (or has some automation in place that is not easily replaceable) and then imports them to CNV;

**Comment by mtessun** [comment]
We should at least document that we do not care about current cloud-init configuration and if it is still needed, it should be "re-added" by the customer after the migration.

I don't see a real demand for this, as I expect that customers heavily using cloud-init also have tooling to create the cloud-init files (aka they are not hand-crafted).

**Comment by pkliczewski** [comment]
Based on information provided by @mtessun I added comment to documentation story to cover this. Closing.
