### ISSUE TITLE
owner of the helper config map

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#176]
I see there is a helper config map for each import, but this config map stays in the system when the VirtualMachineImport gets delete (for example when import in progress).

Shouldn't the owner of this config map be the VirtualMachineImport? Are there other reasources which are created, this could apply to as well?

example config map:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: vmimport.v2v.kubevirt.io98t6w
  generateName: vmimport.v2v.kubevirt.io
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/vmimport.v2v.kubevirt.io98t6w
  uid: 93391a15-f2d6-49f9-a31a-f560e0afa1cd
  resourceVersion: '1480545'
  creationTimestamp: '2020-05-04T13:25:49Z'
  labels:
    vmimport.v2v.kubevirt.io/vmi-name: vm-import-cirrosvm-6kbzp
data:
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
```

**Comment by pkliczewski** [comment]
This should be delete as post import clean up step.

**Comment by atiratree** [comment]
yup, It is currently deleted post import, but not when the VMImport is deleted before it completes. Also setting an OwnerReference is a k8s safe way of deleting things (for example when the vm-import-operator crashes)

**Comment by pkliczewski** [comment]
Yeah, this should be part of the cancellation flow.

**Comment by jakub-dzon** [comment]
Same applies to temporary secret.
