### ISSUE TITLE
Add a step to convert the VM

### ISSUE THREAD

**Issue by ghost** [kubevirt/vm-import-operator#218]
If the source virtual machine provider is not KVM/VirtIO based, e.g. VMware, we should have a step to convert the newly created virtual machine. This should happen between `ImportDisks` and `StartVM`. This cannot be done during the transfer phase where each disk transfer is independent. During the conversion, all the devices, disks and NICs, must be present to correctly create the internal devices definitions in the operating system. 

From an implementation perspective, this could be a job with a pod that mounts all the PVCs under a specific path. This pod would be responsible for the conversion and will most likely wrap `virt-v2v` command to report the progress in a specific format.

**Comment by pkliczewski** [comment]
The PR is merged, closing
