### ISSUE TITLE
Run functional tests in a pod

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#243]
To allow free access to deployed services the tests should be run in a pod (as opposed to using `kubectl port-forward` in test scripts.

Using pod to run tests will bring additional benefit of having stable, universal testing environment.

**Comment by pkliczewski** [comment]
@machacekondra FYI

**Comment by machacekondra** [comment]
The `gocli` `scp` command support only copying *to* local host and not *from*. To have our tests containerised, we need to copy the source code to the node, so we can mount it into the container. The only way to copy the code is to invoke following command: `scp -r  -i ~/sshkey -P ${cluster/cli.sh ports ssh} vm-import-operator/ vagrant@127.0.0.1:/tmp` [sshkey](https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/gocli/cmd/scp.go#L20) which I think could bring more complexity to the automation then, current `port-forwarding`, which is more smooth. So I think we should keep the test execution as is.
