### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/vm-import-operator#254]
In some cases importer pod has `crashloopbackoff` state few moments after it starts, but it turn in running container few moments later. This happens in slow env. We need to ignore those states in order to make the tests non-flaky, because we detect this state and end the import [here](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L332).

**Comment by jakub-dzon** [comment]
What do you think about using some arbitrary threshold on the restart count before we fail the import? There is `ContainerStatus.RestartCount` property.

**Comment by machacekondra** [comment]
That's exactly what I am testing right now :). I propose number of 3, what do you think?

**Comment by jakub-dzon** [comment]
Oh, you're working on it:) I think 3 seems reasonable as default. What do you think about allowing it to be overridden with an env variable?

**Comment by machacekondra** [comment]
Sure, I can add it as env var.
