### ISSUE TITLE
Please fix your periodic

### ISSUE THREAD

**Issue by rmohr** [kubevirt/vm-import-operator#264]
Hey, you are running a periodic job https://prow.apps.ovirt.org/job-history/kubevirt-prow/logs/periodic-vm-import-operator-functional-tests and it is failing since forever. Please fix it or consider removing it, since it does not seem to have any value for you.

**Comment by pkliczewski** [comment]
@rmohr Thanks for reporting. Ondra is looking into it.

**Comment by machacekondra** [comment]
The jobs was temporarily disabled: https://github.com/kubevirt/project-infra/pull/467
