### ISSUE TITLE
Password should be encrypted

### ISSUE THREAD

**Issue by apinnick** [kubevirt/vm-import-operator#275]
RHV engine password should be encrypted.

> stringData:
>   ovirt: |
>     apiUrl: "https://ovirt-engine.example.com:8443/ovirt-engine/api"
>     username: admin@internal # provided in the format of username@domain
>     password: `123456`

**Comment by pkliczewski** [comment]
@apinnick I not sure why do we need it. I see that [CDI](https://github.com/kubevirt/containerized-data-importer/blob/master/manifests/example/endpoint-secret.yaml) is using base64 encoded password. From security perspective there is no difference whether we use base64 or plain text.

**Comment by pkliczewski** [comment]
@apinnick can you point us to other kubevirt projects which use encryption in the secrets?

**Comment by pkliczewski** [comment]
I am closing this issue. Feel free to reopen if you still think it should be fixed.
