### ISSUE TITLE
Add support for importing from VMWare

### ISSUE THREAD

**Issue by mansam** [kubevirt/vm-import-operator#292]
I'm going to work on implementing support for importing VMs from vSphere. As far as I can tell from studying the VM Import Operator code, it's going to involve at least the following things:

1. Update VirtualMachineImport CRD to support a "vmware" key
2. Determine minimum information required to uniquely identify a VM for migration.
3. Possibly refactor where various interfaces live or required methods on interfaces
   * e.g. move SourceClientFactory into client/client.go instead of in the ovirt client package
4. Implement Vmware provider
	* Implement rich client
	* Implement resource mapper
	* Implement template/os finder
5. Make any necessary changes to the virtualmachineimport_controller to support Vmware provider
6. Determine Vmware import validation rules
7. Tests

Before I get too far into the weeds, is there anything it looks like I'm missing or that I should know?

**Comment by masayag** [comment]
Hi @mansam,

- You should also define vmware secret section in the secret resource:
  https://github.com/kubevirt/vm-import-operator/blob/master/docs/design.md#provider-secret
- Importing an image from vmware will require adding support for it on CDI side. Please add a reference to that issue as well.
- Regarding tests, there are two level, unit-tests and functional-tests. For functional tests there is an emulation of ovirt provider at https://github.com/machacekondra/fakeovirt
- Update design documents with the required changes for vmware + add examples of using the new 'vmware' key 
- We'd like to minimize provider specific logic in virtualmachineimport_controller

**Comment by pkliczewski** [comment]
All the PRs are merged. Closing
