### ISSUE TITLE
Add provider label to kubevirt_vmimport metric

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/vm-import-operator#343]
It would be useful to have provider label in kubevirt_vmimport metrics, so user know which provider where successful/failed.

**Comment by pkliczewski** [comment]
@machacekondra Was this fixed by https://github.com/kubevirt/vm-import-operator/pull/328?

**Comment by machacekondra** [comment]
No, it wasn't. I will prepare patch fixing this.

**Comment by pkliczewski** [comment]
Done
