### ISSUE TITLE
Allow user to update OS mapping ConfigMap location without triggerring redeploy

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#356]
To address https://bugzilla.redhat.com/1847810:

New ConfigMap will be introduced to allow users to customize the runtime behaviour of the vm-import-controller, including the namespace and name of the OS mapping ConfigMap. Changes made to the entries in the new config map will be used by the vm-import-controller immediately and without restart. 

The new ConfigMap will reside in the same namespace as the vm-import-controller and will be created by the vm-import-operator if it does not exist. Configuration currently defined on the vm-import-operator level (env variables) will be migrated to the new approach by the operator when the new ConfigMap is created.   
 
The structure of the OS mapping config map will not be changed.
 
The contents of the config map must be stored in must-gather.
 
Design documents and related documentation needs to be updated.

**Comment by pkliczewski** [comment]
Tracked by this [BZ](https://bugzilla.redhat.com/1847810)
