### ISSUE TITLE
Expose the full migration progress in the status

### ISSUE THREAD

**Issue by ghost** [kubevirt/vm-import-operator#362]
Currently, when a virtual machine is imported, the controller adds the conditions to the VirtualMachineImport status. This reflect the current and past states of the import, but not the coming state(s).

In the case of the migration process, it would be interesting to display it as a pipeline, so that the user knows how many steps have to be performed and where the process is over time. Some steps could eventually fail, or be skipped, and this could be represented too. With conditions, the frontend cannot discover the future states, so it's not possible to display the complete pipeline from the start.

The idea is then to store all the possible steps of the migration process in the status, so that the frontend can display it as a pipeline. If the structure is stable and documented, the frontend can _discover_ the data and use various components depending on the information. For example, if a step has a pod attribute, the frontend can expose the pod logs too.

An example of the structure could be (to be discussed):

```
[
  {
    name: "Validation",
    description: "Validation of the virtual machine import request",
    started_on: "2020-08-06 14:05:27 UTC+2",
    finished_on: "2020-08-06 14:05:30 UTC+2",
    progress: 1,
    message: "Validation successful"
  },
  [...]
  {
    name: "Disks Import",
    description: "Importing the disks of the virtual machine",
    started_on: "2020-08-06 14:05:27 UTC+2",
    finished_on: null,
    progress: 0.67,
    message: "Disk import in progress at 543 Mbps"
  },
  {
    name: "OS Conversion",
    description: "Converting the operating system to run on KVM",
    started_on: null,
    finished_on: null,
    progress: null,
    message: null
  },
  [...]
]
```

**Comment by ghost** [comment]
@pkliczewski what's your opinion on adding a dependency on https://github.com/konveyor/controller/tree/master/pkg/itinerary for this enhancement? We use it in Konveyor for VM and Container to represent the workflow in the CR so that UI can discover the steps.

**Comment by pkliczewski** [comment]
Sounds like something we could use
