### ISSUE TITLE
Unknown bios type

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/vm-import-operator#389]
Found by @jelkosz 

In RHV `4.4.2.2` cluster default for bios is set to `q35_sea_bios` and it is returned by the api as:

```xml
    <bios>
        <boot_menu>
            <enabled>false</enabled>
        </boot_menu>
        <type>cluster_default</type>
    </bios>
```

We are unable to understand this setting and map it correctly [here](https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/mapper/mapper.go#L50) which causes `invalid memory address or nil pointer dereference` [here](https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/mapper/mapper.go#L769).

**Comment by pkliczewski** [comment]
It seems like when we see cluster default we need to fetch cluster to understand the bios type. In this specific env there is:

```xml
<bios_type>q35_sea_bios</bios_type>
```

in the cluster description.

**Comment by pkliczewski** [comment]
Related [BZ](https://bugzilla.redhat.com/1875292)

**Comment by jakub-dzon** [comment]
The cluster data is retrieved by the oVirt client (https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/client/ovirt-client.go#L104) and the controller validates the `cluster_default` bios type properly (https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/validation/validators/vm-validator.go#L96); .

The mapper doesn't make use of it, though:
https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/mapper/mapper.go#L529 and https://github.com/kubevirt/vm-import-operator/blob/8a399e89e979c199827e835b5db6e5b64df9bc61/pkg/providers/ovirt/mapper/mapper.go#L766
