### ISSUE TITLE
Shutdown VMs instead of powering them off

### ISSUE THREAD

**Issue by ghost** [kubevirt/vm-import-operator#443]
Currently, during the VMware import, the VM is powered off: https://github.com/kubevirt/vm-import-operator/blob/master/pkg/providers/vmware/client/client.go#L180-L198. And it can impact the filesystem as this function acts as pulling the power cord.

Instead, the VM should be shutdown: https://github.com/vmware/govmomi/blob/master/govc/host/shutdown.go. And, if the VM is not off after 15 minutes, the import should fail to avoid any issue with the fielsystems.

**Comment by mansam** [comment]
@fdupont-redhat the oVirt provider has a 5 minute timeout for shutting down. What do you think about aligning the vSphere provider with that instead of 15 minutes?

**Comment by ghost** [comment]
@mansam I'm fine with 5 minutes.
