### ISSUE TITLE
CM and Secret is re-created even if successful import

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/vm-import-operator#63]
It's because, when `CreateMapper` is called we always ensure if creds are created, but after successful import we remove them and another reconcile is called. We need to make sure CreateMapper don't create cm/secret if not needed.

**Comment by jakub-dzon** [comment]
I think we should completely skip the reconciliation if the import was successful (the import has proper status condition). 
Also - the import shouldn't be re-queued after it succeeds. Were there any errors that might have caused the event to be re-queued?

**Comment by pkliczewski** [comment]
@jakub-dzon You seem to describe how to fix the issue

**Comment by machacekondra** [comment]
With #70 in place it don't happen anymore. But I'll keep this one open, so we add condition to don't reconcile, if status is success.

**Comment by pkliczewski** [comment]
PR #70 is merged so closing
