### ISSUE TITLE
Don't reconnect to target infra if not needed

### ISSUE THREAD

**Issue by machacekondra** [kubevirt/vm-import-operator#64]
It may be very time consuming to connect to target infra, so don't connect there if not needed.

**Comment by pkliczewski** [comment]
Please provide more info when we allow to reconnect?

**Comment by jakub-dzon** [comment]
@machacekondra - can you describe in more detail what you meant?

**Comment by machacekondra** [comment]
We call initProvider each time reconcile is invoked. But we need to call it only once to fetch VM to validate it and map it, later when disks are  being copied, and we only monitor status, it's not needed to call initProvider anymore, it would need some refactoring of the provider module. It would improve performance in case the connection is expensive.
