### ISSUE TITLE
Data Volume creation failure is reported as success in Virtual Machine Import status conditions

### ISSUE THREAD

**Issue by jakub-dzon** [kubevirt/vm-import-operator#73]
Was: `status: "True"`; should be `status: "False"`

```
 - lastHeartbeatTime: "2020-04-09T14:45:04Z"
      lastTransitionTime: "2020-04-09T14:45:03Z"
      message: 'Data volume creationg faield: admission webhook "datavolume-validate.cdi.kubevirt.io"
        denied the request:  Missing Data volume source'
      reason: DataVolumeCreationFailed
      status: "True"
      type: Succeeded
```

**Comment by jakub-dzon** [comment]
The failure itself is caused _probably_ by my dev env lacking CDI with support for Imageio.

**Comment by pkliczewski** [comment]
@jakub-dzon which version of CDI are you using?

**Comment by jakub-dzon** [comment]
So far one bundled with HCO 2.2.0-5.

**Comment by pkliczewski** [comment]
As far as I can [see](https://github.com/kubevirt/hyperconverged-cluster-operator/releases/tag/v0.2.2) this version was released long time ago. I suggest to update CDI and it should work.

Edit: it seems like I checked upstream :disappointed: but as I can say 2.2 is old and it won't contain Ondra's changes.
