### ISSUE TITLE
The owner of DataVolumes should be the VM after successful import

### ISSUE THREAD

**Issue by atiratree** [kubevirt/vm-import-operator#74]

**Comment by pkliczewski** [comment]
@suomiy Is this default behavior?

**Comment by atiratree** [comment]
for DVs created by UI, yes

**Comment by atiratree** [comment]
shouldn't the owner of VirtualMachineImport be the VM as well after successful import? 
As there is probably not a reason to keep it live once somebody deletes the VM

**Comment by pkliczewski** [comment]
No owner reference for imported VM is intentional. We want the user to be able to delete `VirtualMachineImport` without delete VM.

Is there any logic in the UI which relies on DVs to VM owner reference?

**Comment by atiratree** [comment]
> No owner reference for imported VM is intentional. We want the user to be able to delete VirtualMachineImport without delete VM.

That would still be possible if the owner of VMImport is VM.

> Is there any logic in the UI which relies on DVs to VM owner reference?

- VM removal - will delete the disks as well
- also disk removal - which is buggy currently, but we have a bug for it and will be fixed soon . There will be a confirmation dialog.

And we cannot delete the datavolume if we are not sure the VM doesn't own it.

**Comment by pkliczewski** [comment]
> That would still be possible if the owner of VMImport is VM.

This is actually the other way around.

> And we cannot delete the datavolume if we are not sure the VM doesn't own it.

Make sense. Let's fix it.

**Comment by atiratree** [comment]
> > That would still be possible if the owner of VMImport is VM.
> 
> This is actually the other way around.

Ik, I am just wondering if it would make sense to switch it after the import completes. I guess we can  delete the ref and keep it hanging - not good cleanup-wise.
