### ISSUE TITLE
Source vm is always stopped

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/vm-import-operator#78]
While working on controller tests I noticed that we always [attempt](https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L171) to stop vm without checking its status first

**Comment by jakub-dzon** [comment]
In case of oVirt, we check it [in the oVirt client](https://github.com/kubevirt/vm-import-operator/blob/f43f8c786314cea675845fb7717da81f1b94e70c/pkg/providers/ovirt/client/ovirt-client.go#L122). 

IMO from controller perspective the result is important - a stopped VM and it is up to the provider to make it optimal.

**Comment by pkliczewski** [comment]
Good point, the question is why not to do it earlier since we already have [vm status](https://github.com/kubevirt/vm-import-operator/blob/f43f8c786314cea675845fb7717da81f1b94e70c/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L789). It would save us one call to oVirt.

**Comment by jakub-dzon** [comment]
That's true. The risk of a stopped machine starting between the initial vm load and that point in code seems to be low (unless resource mapping checks get stuck on the calls to the cluster); with mass migration every outbound call counts.

Maybe the provider can make the suggested local check - it owns VM and oVirtClient.
